site_name: Руководство IT Кластера

theme:
  logo: logo.svg
  favicon: logo.svg
  language: ru
  name: material
  custom_dir: overrides

  features:
    - navigation.tabs

  palette:
    primary: indigo

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
  - _css/style.css