site_name: Руководство IT Кластера

theme:
  logo: logo.svg
  favicon: logo.svg
  language: ru
  name: material
  custom_dir: overrides

  features:
    - navigation.tabs

  palette:
    primary: indigo

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - О платформе: index.md
  - Компаниям:
    - Регистрация: Компаниям/index.md
    - Авторизация: Компаниям/Авторизация.md
    - Потребности:
      - О потребностях: Компаниям/Потребности/index.md
      - Страница потребностей: Компаниям/Потребности/Страница.md
  - Образовательным учреждениям:
    - Регистрация: Образовательным учреждениям/index.md
    - Авторизация: Образовательным учреждениям/Авторизация.md
  - Студентам:
    - Регистрация: Студентам/index.md
    - Авторизация: Студентам/Авторизация.md
    - Потребности:
      - Просмотр потребностей: Студентам/Потребности/Потребности.md

extra_css:
  - _css/style.css